feat: Realtime using accessToken callback for auth
supabase/supabase-js pull request #1320
Opened 2024-12-03 21:21 UTC by filipecabaco

## What kind of change does this PR introduce?

Realtime using accessToken callback for auth

2024-12-04 20:02 UTC, grdsdev requested changes

2024-12-04 20:02 UTC, grdsdev commented on src/SupabaseClient.ts
> +      accessToken: this.accessToken,
You probably want to forward the call to `_getAccessToken` method.

2024-12-05 13:15 UTC, grdsdev approved these changes

2024-12-05 15:00 UTC, merged

2024-12-05 21:58 UTC, blechatellier commented
The latest release is causing a "Maximum call stack size exceeded" error.

```
Unhandled Runtime Error

RangeError: Maximum call stack size exceeded

Call Stack
<unknown>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
push.[project]/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js [app-client] (ecmascript).__awaiter
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
RealtimeClient._getAccessToken [as accessToken]
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (268:32)
RealtimeClient.<anonymous>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (270:25)
<unknown>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
push.[project]/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js [app-client] (ecmascript).__awaiter
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
RealtimeClient._getAccessToken [as accessToken]
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (268:32)
RealtimeClient.<anonymous>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (270:25)
<unknown>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
push.[project]/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js [app-client] (ecmascript).__awaiter
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
RealtimeClient._getAccessToken [as accessToken]
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (268:32)
RealtimeClient.<anonymous>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (270:25)
<unknown>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
push.[project]/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js [app-client] (ecmascript).__awaiter
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
RealtimeClient._getAccessToken [as accessToken]
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (268:32)
RealtimeClient.<anonymous>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (270:25)
<unknown>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
push.[project]/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js [app-client] (ecmascript).__awaiter
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
RealtimeClient._getAccessToken [as accessToken]
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (268:32)
RealtimeClient.<anonymous>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (270:25)
<unknown>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
push.[project]/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js [app-client] (ecmascript).__awaiter
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
RealtimeClient._getAccessToken [as accessToken]
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (268:32)
RealtimeClient.<anonymous>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (270:25)
<unknown>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
push.[project]/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js [app-client] (ecmascript).__awaiter
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
RealtimeClient._getAccessToken [as accessToken]
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (268:32)
RealtimeClient.<anonymous>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (270:25)
<unknown>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
push.[project]/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js [app-client] (ecmascript).__awaiter
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
RealtimeClient._getAccessToken [as accessToken]
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (268:32)
RealtimeClient.<anonymous>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (270:25)
<unknown>
node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts (23:62)
```